#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
                ref class ScrollViewer;
                ref class StackPanel;
                ref class ListBox;
                ref class RowDefinition;
                ref class TextBox;
                ref class Button;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}

namespace VBA10
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class CheatPane : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::VisualState^ wideView;
        private: ::Windows::UI::Xaml::VisualState^ mediumView;
        private: ::Windows::UI::Xaml::VisualState^ narrowView;
        private: ::Windows::UI::Xaml::Controls::Grid^ titleBar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtNoROM;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ svMain;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ panelAddCode;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ panelCheatList;
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ cvsAllCheats;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtNoCheat;
        private: ::Windows::UI::Xaml::Controls::ListBox^ cheatList;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ descLabel;
        private: ::Windows::UI::Xaml::Controls::RowDefinition^ rowCode;
        private: ::Windows::UI::Xaml::Controls::TextBox^ descBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ codeBox;
        private: ::Windows::UI::Xaml::Controls::Button^ addButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ title;
    };
}

