#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class SplitView;
                ref class StackPanel;
                ref class TextBlock;
                ref class Button;
                ref class Frame;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                namespace Primitives {
                    ref class ToggleButton;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}
namespace VBA10 {
    namespace Controls {
        ref class NavMenuListView;
    }
}

namespace VBA10
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
        class DirectXPage_obj2_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::VisualState^ wideView;
        private: ::Windows::UI::Xaml::VisualState^ mediumView;
        private: ::Windows::UI::Xaml::VisualState^ narrowView;
        private: ::Windows::UI::Xaml::Controls::SplitView^ RootSplitView;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ TogglePaneButton;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ panelEditButton;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ notificationPanel;
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ notificationEntrance;
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ notificationExit;
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ notificationEntranceExit;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtNotification;
        private: ::Windows::UI::Xaml::Controls::Button^ CancelPositionBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ AcceptPositionBtn;
        private: ::VBA10::Controls::NavMenuListView^ NavMenuList;
        private: ::Windows::UI::Xaml::Controls::Frame^ contentFrame;
    };
}

