#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class ListBox;
                ref class Button;
                ref class AppBarButton;
            }
        }
    }
}

namespace VBA10
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class FileBrowserPane : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ FileListvs;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtLoading;
        private: ::Windows::UI::Xaml::Controls::ListBox^ fileList;
        private: ::Windows::UI::Xaml::Controls::Button^ closeBtn;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ backBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtCurrentFolder;
    };
}

