#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBlock;
                ref class Grid;
                ref class TextBox;
            }
        }
    }
}

namespace VBA10
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class HIDGamepadConfig : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ closeBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtNotification;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridMain;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtLeft1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtLeft2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtRight1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtRight2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtUp1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtUp2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtDown1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtDown2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtA1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtA2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtB1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtB2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtL1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtL2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtR1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtR2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtStart1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtStart2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtSelect1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtSelect2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtTurbo1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtTurbo2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtTitle;
    };
}

