//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "HIDGamepadConfig.xaml.h"

void ::VBA10::HIDGamepadConfig::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///HIDGamepadConfig.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::VBA10::HIDGamepadConfig::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->closeBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->closeBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::closeBtn_Click);
            }
            break;
        case 2:
            {
                this->txtNotification = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 3:
            {
                this->gridMain = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 4:
            {
                this->txtLeft1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtLeft1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtLeft1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 5:
            {
                this->txtLeft2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtLeft2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtLeft2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 6:
            {
                this->txtRight1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtRight1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtRight1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 7:
            {
                this->txtRight2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtRight2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtRight2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 8:
            {
                this->txtUp1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtUp1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtUp1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 9:
            {
                this->txtUp2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtUp2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtUp2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 10:
            {
                this->txtDown1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtDown1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtDown1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 11:
            {
                this->txtDown2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtDown2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtDown2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 12:
            {
                this->txtA1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtA1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtA1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 13:
            {
                this->txtA2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtA2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtA2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 14:
            {
                this->txtB1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtB1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtB1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 15:
            {
                this->txtB2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtB2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtB2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 16:
            {
                this->txtL1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtL1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtL1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 17:
            {
                this->txtL2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtL2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtL2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 18:
            {
                this->txtR1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtR1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtR1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 19:
            {
                this->txtR2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtR2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtR2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 20:
            {
                this->txtStart1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtStart1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtStart1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 21:
            {
                this->txtStart2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtStart2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtStart2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 22:
            {
                this->txtSelect1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtSelect1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtSelect1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 23:
            {
                this->txtSelect2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtSelect2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtSelect2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 24:
            {
                this->txtTurbo1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtTurbo1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtTurbo1))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 25:
            {
                this->txtTurbo2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtTurbo2))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_GotFocus);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtTurbo2))->LostFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::HIDGamepadConfig::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HIDGamepadConfig::txtLeft1_LostFocus);
            }
            break;
        case 26:
            {
                this->txtTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::VBA10::HIDGamepadConfig::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


