#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class CommandBar;
                ref class ScrollViewer;
                ref class Button;
                ref class ListBox;
                ref class Image;
                ref class TextBlock;
                ref class AppBarButton;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}

namespace VBA10
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class SelectROMPane : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::VisualState^ wideView;
        private: ::Windows::UI::Xaml::VisualState^ mediumView;
        private: ::Windows::UI::Xaml::VisualState^ narrowView;
        private: ::Windows::UI::Xaml::Controls::CommandBar^ topbar;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ svContainer;
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ cvsAllROMEntries;
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ cvsLastROMEntry;
        private: ::Windows::UI::Xaml::Controls::Button^ lastRomGrid;
        private: ::Windows::UI::Xaml::Controls::ListBox^ romList;
        private: ::Windows::UI::Xaml::Controls::Button^ addROMbtn;
        private: ::Windows::UI::Xaml::Controls::Image^ lastRomImage;
        private: ::Windows::UI::Xaml::Controls::Image^ imgPlay;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtLastROM;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ saveBtn;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ selectStateBtn;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ resetBtn;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ loadBtn;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ spacerBtn;
    };
}

