//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "SelectROMPane.xaml.h"

void ::VBA10::SelectROMPane::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///SelectROMPane.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::VBA10::SelectROMPane::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 2:
            {
                this->LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 3:
            {
                this->wideView = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
            }
            break;
        case 4:
            {
                this->mediumView = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
            }
            break;
        case 5:
            {
                this->narrowView = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
            }
            break;
        case 6:
            {
                this->topbar = safe_cast<::Windows::UI::Xaml::Controls::CommandBar^>(__target);
            }
            break;
        case 7:
            {
                this->svContainer = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(__target);
            }
            break;
        case 8:
            {
                this->cvsAllROMEntries = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(__target);
            }
            break;
        case 9:
            {
                this->cvsLastROMEntry = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(__target);
            }
            break;
        case 10:
            {
                this->lastRomGrid = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->lastRomGrid))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&SelectROMPane::lastRomImage_Tapped);
            }
            break;
        case 11:
            {
                this->romList = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(this->romList))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SelectROMPane::romList_SelectionChanged);
            }
            break;
        case 12:
            {
                this->addROMbtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->addROMbtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectROMPane::addROMbtn_Click);
            }
            break;
        case 13:
            {
                ::Windows::UI::Xaml::Controls::Grid^ element13 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(element13))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&SelectROMPane::lbAllROMMainGrid_RightTapped);
            }
            break;
        case 14:
            {
                ::Windows::UI::Xaml::Controls::Button^ element14 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element14))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectROMPane::ContextMenuBtn_Click);
            }
            break;
        case 15:
            {
                this->lastRomImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 16:
            {
                this->imgPlay = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 17:
            {
                this->txtLastROM = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 18:
            {
                this->saveBtn = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->saveBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectROMPane::saveBtn_Click);
            }
            break;
        case 19:
            {
                this->selectStateBtn = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->selectStateBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectROMPane::selectStateBtn_Click);
            }
            break;
        case 20:
            {
                this->resetBtn = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->resetBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectROMPane::resetBtn_Click);
            }
            break;
        case 21:
            {
                this->loadBtn = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->loadBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectROMPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectROMPane::loadBtn_Click);
            }
            break;
        case 22:
            {
                this->spacerBtn = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::VBA10::SelectROMPane::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


