//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "SelectFilesPane.xaml.h"

void ::VBA10::SelectFilesPane::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///SelectFilesPane.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::VBA10::SelectFilesPane::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->FileListvs = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(__target);
            }
            break;
        case 2:
            {
                this->txtNoFile = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 3:
            {
                this->fileList = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
            }
            break;
        case 4:
            {
                this->CancelBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->CancelBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectFilesPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectFilesPane::CancelBtn_Click);
            }
            break;
        case 5:
            {
                this->OkBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->OkBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SelectFilesPane::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SelectFilesPane::OkBtn_Click);
            }
            break;
        case 6:
            {
                this->txtTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::VBA10::SelectFilesPane::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


