//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "SettingsPage.xaml.h"

void ::VBA10::SettingsPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///SettingsPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::VBA10::SettingsPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 2:
            {
                this->titleBar = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 3:
            {
                this->soundToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->soundToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::soundToggle_Toggled);
            }
            break;
        case 4:
            {
                this->soundSyncToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->soundSyncToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::soundSyncToggle_Toggled_1);
            }
            break;
        case 5:
            {
                this->saveConfirmationToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->saveConfirmationToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::saveConfirmationToggle_Toggled_1);
            }
            break;
        case 6:
            {
                this->loadConfirmationToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->loadConfirmationToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::loadConfirmationToggle_Toggled_1);
            }
            break;
        case 7:
            {
                this->cboTheme = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->cboTheme))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::cboTheme_SelectionChanged);
            }
            break;
        case 8:
            {
                this->cboCommandButtonPosition = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->cboCommandButtonPosition))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::cboCommandButtonPosition_SelectionChanged);
            }
            break;
        case 9:
            {
                this->hideHamburgerToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->hideHamburgerToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::hideHamburgerToggle_Toggled);
            }
            break;
        case 10:
            {
                this->enableTurboToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->enableTurboToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::enableTurboToggle_Toggled);
            }
            break;
        case 11:
            {
                this->skipComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->skipComboBox))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::skipComboBox_SelectionChanged);
            }
            break;
        case 12:
            {
                this->turboSkipComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->turboSkipComboBox))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::turboSkipComboBox_SelectionChanged_1);
            }
            break;
        case 13:
            {
                this->cboPixelFilter = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->cboPixelFilter))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::cboPixelFilter_SelectionChanged);
            }
            break;
        case 14:
            {
                this->cboPixelShader = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->cboPixelShader))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::cboPixelShader_SelectionChanged);
            }
            break;
        case 15:
            {
                this->monitorComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->monitorComboBox))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::monitorComboBox_SelectionChanged_1);
            }
            break;
        case 16:
            {
                this->aspectComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->aspectComboBox))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::aspectComboBox_SelectionChanged_1);
            }
            break;
        case 17:
            {
                this->fpsToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->fpsToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::fpsToggle_Toggled);
            }
            break;
        case 18:
            {
                this->fullscreenToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->fullscreenToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::fullscreenToggle_Toggled);
            }
            break;
        case 19:
            {
                this->InputStackPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 20:
            {
                this->vsControllerList = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(__target);
            }
            break;
        case 21:
            {
                this->txtControllerStatus = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 22:
            {
                this->ConfigureXboxBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ConfigureXboxBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::ConfigureXboxBtn_Click);
            }
            break;
        case 23:
            {
                this->panelHIDGamepad = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 24:
            {
                this->cboTurboBehavior = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->cboTurboBehavior))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::cboTurboBehavior_SelectionChanged);
            }
            break;
        case 25:
            {
                this->touchToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->touchToggle))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::touchToggle_Toggled);
            }
            break;
        case 26:
            {
                this->dpadComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->dpadComboBox))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SettingsPage::dpadComboBox_SelectionChanged_1);
            }
            break;
        case 27:
            {
                this->editButonLayoutBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->editButonLayoutBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::editButonLayoutBtn_Click);
            }
            break;
        case 28:
            {
                this->leftKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->leftKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->leftKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::leftKeyBox_KeyUp);
            }
            break;
        case 29:
            {
                this->upKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->upKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->upKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::upKeyBox_KeyUp);
            }
            break;
        case 30:
            {
                this->rightKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->rightKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->rightKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::rightKeyBox_KeyUp);
            }
            break;
        case 31:
            {
                this->downKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->downKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->downKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::downKeyBox_KeyUp);
            }
            break;
        case 32:
            {
                this->bKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->bKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->bKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::bKeyBox_KeyUp);
            }
            break;
        case 33:
            {
                this->aKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->aKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->aKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::aKeyBox_KeyUp);
            }
            break;
        case 34:
            {
                this->lKeyLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 35:
            {
                this->lKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->lKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->lKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::lKeyBox_KeyUp);
            }
            break;
        case 36:
            {
                this->rKeyLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 37:
            {
                this->rKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->rKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->rKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::rKeyBox_KeyUp);
            }
            break;
        case 38:
            {
                this->startKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->startKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->startKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::startKeyBox_KeyUp);
            }
            break;
        case 39:
            {
                this->selectKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->selectKeyBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->selectKeyBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::selectKeyBox_KeyUp);
            }
            break;
        case 40:
            {
                this->turboModeBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->turboModeBox))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::keyDown);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->turboModeBox))->KeyUp += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&SettingsPage::turboModeBox_KeyUp_1);
            }
            break;
        case 41:
            {
                this->controllerOpacitySlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->controllerOpacitySlider))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&SettingsPage::controllerOpacitySlider_ValueChanged_1);
            }
            break;
        case 42:
            {
                this->controllerOpacityToggle = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(__target);
            }
            break;
        case 43:
            {
                this->buttonScaleSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->buttonScaleSlider))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&SettingsPage::buttonScaleSlider_ValueChanged_1);
            }
            break;
        case 44:
            {
                this->buttonScaleToggle = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(__target);
            }
            break;
        case 45:
            {
                this->controllerScaleSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->controllerScaleSlider))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&SettingsPage::controllerScaleSlider_ValueChanged_1);
            }
            break;
        case 46:
            {
                this->controllerScaleToggle = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(__target);
            }
            break;
        case 47:
            {
                this->deadzoneSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->deadzoneSlider))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&SettingsPage::deadzoneSlider_ValueChanged_1);
            }
            break;
        case 48:
            {
                this->deadzoneToggle = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(__target);
            }
            break;
        case 49:
            {
                this->txtHIDGamepad = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 50:
            {
                this->lbHIDGamepad = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
            }
            break;
        case 51:
            {
                this->panelHIDConnect = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 52:
            {
                this->ConfigureBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ConfigureBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::ConfigureBtn_Click);
            }
            break;
        case 53:
            {
                this->ConnectBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ConnectBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VBA10::SettingsPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&SettingsPage::ConnectBtn_Click);
            }
            break;
        case 54:
            {
                this->title = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::VBA10::SettingsPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


