#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class Grid;
                ref class ComboBox;
                ref class TextBlock;
            }
        }
    }
}

namespace VBA10
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class XboxConfigPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ CancelBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ OkBtn;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridMain;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboA;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboB;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboX;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboY;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboL1;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboL2;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboR1;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboR2;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboL3;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboR3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtTitle;
    };
}

